version: "3"
services:
  app:
    image: soloidx/n5_assessment
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - "WAIT_HOSTS=db:5432"
    env_file: ./docker/docker.env
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
#    ports:
#      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=n5_pg_pass"
      - "POSTGRES_USER=n5_pg_user"
      - "POSTGRES_DB=assessment_db"
