# Generated by Django 4.1.6 on 2023-02-14 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transit_tickets", "0002_ticket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="datetime",
            new_name="infraction_date",
        ),
    ]
