# Generated by Django 4.1.6 on 2023-02-14 02:51

from django.db import migrations, models
import django.db.models.deletion
import transit_tickets.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("transit_tickets", "0003_rename_datetime_ticket_infraction_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficerToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.UUID("6740aed9-0dd7-4161-a5f3-0611eb591a26")
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        default=transit_tickets.models.default_expiration_date
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transit_tickets.officer",
                    ),
                ),
            ],
        ),
    ]
