# Generated by Django 4.1.6 on 2023-02-14 04:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("transit_tickets", "0004_officertoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="email",
            field=models.EmailField(
                default="1676347706.694004@mail.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="officer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="transit_tickets.officer",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="officertoken",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("de991cc7-88b6-4bd8-91fd-5f6ad1b5ea8e")
            ),
        ),
    ]
